# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 1200)
        MainWindow.setMinimumSize(QtCore.QSize(1800, 1200))
        MainWindow.setMaximumSize(QtCore.QSize(1800, 1200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1801, 1201))
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.frame = QtWidgets.QFrame(self.login_page)
        self.frame.setGeometry(QtCore.QRect(10, -10, 1801, 1201))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(500, -140, 771, 631))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("ui/logo.jpg"))
        self.logo.setScaledContents(True)
        self.logo.setWordWrap(False)
        self.logo.setObjectName("logo")
        self.mail_input = QtWidgets.QTextEdit(self.frame)
        self.mail_input.setGeometry(QtCore.QRect(650, 390, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mail_input.setFont(font)
        self.mail_input.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.mail_input.setTabStopWidth(20)
        self.mail_input.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.mail_input.setPlaceholderText("example@company.com")
        self.mail_input.setObjectName("mail_input")
        self.password_input = QtWidgets.QTextEdit(self.frame)
        self.password_input.setGeometry(QtCore.QRect(650, 460, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password_input.setFont(font)
        self.password_input.setAutoFillBackground(False)
        self.password_input.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.password_input.setTabStopWidth(15)
        self.password_input.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.password_input.setPlaceholderText("password")
        self.password_input.setObjectName("password_input")
        self.enter_button = QtWidgets.QPushButton(self.frame)
        self.enter_button.setGeometry(QtCore.QRect(750, 650, 321, 91))
        self.enter_button.setStyleSheet("background-color: rgb(103, 39, 39);\n"
"font: 25 18pt \"Segoe UI Light\";\n"
"color: rgb(255,255,255);\n"
"\n"
"border-radius : 15px;")
        self.enter_button.setObjectName("enter_button")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(170, 910, 1461, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.logo_3 = QtWidgets.QLabel(self.frame)
        self.logo_3.setGeometry(QtCore.QRect(460, 990, 451, 121))
        self.logo_3.setText("")
        self.logo_3.setPixmap(QtGui.QPixmap("ui/company_logo_2.png"))
        self.logo_3.setScaledContents(True)
        self.logo_3.setWordWrap(False)
        self.logo_3.setObjectName("logo_3")
        self.logo_4 = QtWidgets.QLabel(self.frame)
        self.logo_4.setGeometry(QtCore.QRect(1070, 960, 181, 181))
        self.logo_4.setText("")
        self.logo_4.setPixmap(QtGui.QPixmap("ui/company_logo_3.png"))
        self.logo_4.setScaledContents(True)
        self.logo_4.setWordWrap(False)
        self.logo_4.setObjectName("logo_4")
        self.logo_5 = QtWidgets.QLabel(self.frame)
        self.logo_5.setGeometry(QtCore.QRect(1500, 970, 191, 181))
        self.logo_5.setText("")
        self.logo_5.setPixmap(QtGui.QPixmap("ui/company_logo_4.jpg"))
        self.logo_5.setScaledContents(True)
        self.logo_5.setWordWrap(False)
        self.logo_5.setObjectName("logo_5")
        self.logo_6 = QtWidgets.QLabel(self.frame)
        self.logo_6.setGeometry(QtCore.QRect(140, 980, 271, 121))
        self.logo_6.setText("")
        self.logo_6.setPixmap(QtGui.QPixmap("ui/company_logo_6.png"))
        self.logo_6.setScaledContents(True)
        self.logo_6.setWordWrap(False)
        self.logo_6.setObjectName("logo_6")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(810, 930, 241, 31))
        self.label.setStyleSheet("font: italic 14pt \"MS Sans Serif\";\n"
"color : rgb(105, 105, 105);")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.login_page)
        self.user_page = QtWidgets.QWidget()
        self.user_page.setObjectName("user_page")
        self.frame_2 = QtWidgets.QFrame(self.user_page)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1801, 1201))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(240, 110, 1621, 1251))
        self.frame_3.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"border-radius: 50px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget_2.setGeometry(QtCore.QRect(30, -10, 1511, 1091))
        self.stackedWidget_2.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"border-radius: 50px;")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_5 = QtWidgets.QFrame(self.page)
        self.frame_5.setGeometry(QtCore.QRect(20, 380, 1461, 691))
        self.frame_5.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.frame_5)
        self.webEngineView.setGeometry(QtCore.QRect(0, 20, 1461, 651))
        self.webEngineView.setStyleSheet("border-radius : 20px;")
        self.webEngineView.setUrl(QtCore.QUrl("https://www.wsj.com/market-data/stocks"))
        self.webEngineView.setZoomFactor(1.2)
        self.webEngineView.setObjectName("webEngineView")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(470, 20, 651, 341))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("ui/background.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(480, 20, 471, 141))
        self.label_7.setStyleSheet("font: 75 25pt \"Nirmala UI\";\n"
"color: rgb(139, 139, 139);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(770, 130, 161, 23))
        self.label_8.setStyleSheet("font: italic 8pt \"Segoe UI Semilight\";")
        self.label_8.setObjectName("label_8")
        self.frame_6 = QtWidgets.QFrame(self.page_2)
        self.frame_6.setGeometry(QtCore.QRect(60, 220, 661, 371))
        self.frame_6.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(40, 10, 541, 51))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.webEngineView_2 = QtWebEngineWidgets.QWebEngineView(self.frame_6)
        self.webEngineView_2.setGeometry(QtCore.QRect(20, 70, 621, 281))
        self.webEngineView_2.setStyleSheet("https://www.coursera.org/specializations/investment-portolio-management")
        self.webEngineView_2.setUrl(QtCore.QUrl("https://www.coursera.org/specializations/investment-portolio-management"))
        self.webEngineView_2.setZoomFactor(0.7)
        self.webEngineView_2.setObjectName("webEngineView_2")
        self.frame_7 = QtWidgets.QFrame(self.page_2)
        self.frame_7.setGeometry(QtCore.QRect(760, 220, 661, 371))
        self.frame_7.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setGeometry(QtCore.QRect(30, 10, 581, 51))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.webEngineView_3 = QtWebEngineWidgets.QWebEngineView(self.frame_7)
        self.webEngineView_3.setGeometry(QtCore.QRect(10, 70, 621, 281))
        self.webEngineView_3.setStyleSheet("https://www.coursera.org/specializations/investment-portolio-management")
        self.webEngineView_3.setUrl(QtCore.QUrl("https://www.coursera.org/learn/advanced-valuation-and-strategy"))
        self.webEngineView_3.setZoomFactor(0.7)
        self.webEngineView_3.setObjectName("webEngineView_3")
        self.frame_8 = QtWidgets.QFrame(self.page_2)
        self.frame_8.setGeometry(QtCore.QRect(60, 640, 661, 371))
        self.frame_8.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(160, 240, 661, 371))
        self.frame_9.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setGeometry(QtCore.QRect(40, 10, 541, 51))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.webEngineView_4 = QtWebEngineWidgets.QWebEngineView(self.frame_8)
        self.webEngineView_4.setGeometry(QtCore.QRect(20, 80, 621, 281))
        self.webEngineView_4.setStyleSheet("https://www.coursera.org/specializations/investment-portolio-management")
        self.webEngineView_4.setUrl(QtCore.QUrl("https://www.coursera.org/specializations/financial-management"))
        self.webEngineView_4.setZoomFactor(0.7)
        self.webEngineView_4.setObjectName("webEngineView_4")
        self.frame_10 = QtWidgets.QFrame(self.page_2)
        self.frame_10.setGeometry(QtCore.QRect(760, 640, 661, 371))
        self.frame_10.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setGeometry(QtCore.QRect(160, 240, 661, 371))
        self.frame_12.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        self.label_12.setGeometry(QtCore.QRect(40, 10, 581, 51))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.webEngineView_5 = QtWebEngineWidgets.QWebEngineView(self.frame_10)
        self.webEngineView_5.setGeometry(QtCore.QRect(20, 70, 621, 281))
        self.webEngineView_5.setStyleSheet("https://www.coursera.org/specializations/investment-portolio-management")
        self.webEngineView_5.setUrl(QtCore.QUrl("https://www.coursera.org/learn/wharton-cryptocurrency-blockchain-introduction-digital-currency?=&page=1"))
        self.webEngineView_5.setZoomFactor(0.7)
        self.webEngineView_5.setObjectName("webEngineView_5")
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.scrollArea = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea.setGeometry(QtCore.QRect(2, 82, 1501, 991))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 2480, 930))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_13.setEnabled(True)
        self.frame_13.setMinimumSize(QtCore.QSize(400, 900))
        self.frame_13.setMaximumSize(QtCore.QSize(400, 900))
        self.frame_13.setStyleSheet("background-color : rgb(156, 82, 84);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        self.label_6.setGeometry(QtCore.QRect(90, 50, 221, 211))
        self.label_6.setStyleSheet("border-radius:20px;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("ui/john.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.PersonelName = QtWidgets.QLabel(self.frame_13)
        self.PersonelName.setGeometry(QtCore.QRect(90, 280, 211, 51))
        self.PersonelName.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName.setObjectName("PersonelName")
        self.PersonelName_2 = QtWidgets.QLabel(self.frame_13)
        self.PersonelName_2.setGeometry(QtCore.QRect(30, 330, 341, 51))
        self.PersonelName_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_2.setObjectName("PersonelName_2")
        self.PersonelName_3 = QtWidgets.QLabel(self.frame_13)
        self.PersonelName_3.setGeometry(QtCore.QRect(90, 400, 211, 51))
        self.PersonelName_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_3.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_3.setObjectName("PersonelName_3")
        self.PersonelName_4 = QtWidgets.QLabel(self.frame_13)
        self.PersonelName_4.setGeometry(QtCore.QRect(30, 460, 341, 51))
        self.PersonelName_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_4.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_4.setObjectName("PersonelName_4")
        self.personel_send_mail = QtWidgets.QPushButton(self.frame_13)
        self.personel_send_mail.setGeometry(QtCore.QRect(30, 720, 341, 61))
        self.personel_send_mail.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail.setObjectName("personel_send_mail")
        self.personal_message = QtWidgets.QPushButton(self.frame_13)
        self.personal_message.setGeometry(QtCore.QRect(30, 790, 341, 61))
        self.personal_message.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personal_message.setObjectName("personal_message")
        self.personel_send_mail_2 = QtWidgets.QPushButton(self.frame_13)
        self.personel_send_mail_2.setGeometry(QtCore.QRect(30, 570, 341, 61))
        self.personel_send_mail_2.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail_2.setObjectName("personel_send_mail_2")
        self.horizontalLayout.addWidget(self.frame_13)
        self.frame_15 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_15.setEnabled(True)
        self.frame_15.setMinimumSize(QtCore.QSize(400, 900))
        self.frame_15.setMaximumSize(QtCore.QSize(400, 900))
        self.frame_15.setStyleSheet("background-color : rgb(156, 82, 84);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        self.label_15.setGeometry(QtCore.QRect(90, 50, 221, 211))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("ui/clara.jpg"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.PersonelName_13 = QtWidgets.QLabel(self.frame_15)
        self.PersonelName_13.setGeometry(QtCore.QRect(70, 280, 261, 51))
        self.PersonelName_13.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_13.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_13.setObjectName("PersonelName_13")
        self.PersonelName_14 = QtWidgets.QLabel(self.frame_15)
        self.PersonelName_14.setGeometry(QtCore.QRect(90, 330, 211, 51))
        self.PersonelName_14.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_14.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_14.setObjectName("PersonelName_14")
        self.PersonelName_15 = QtWidgets.QLabel(self.frame_15)
        self.PersonelName_15.setGeometry(QtCore.QRect(90, 400, 211, 51))
        self.PersonelName_15.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_15.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_15.setObjectName("PersonelName_15")
        self.PersonelName_16 = QtWidgets.QLabel(self.frame_15)
        self.PersonelName_16.setGeometry(QtCore.QRect(30, 460, 341, 51))
        self.PersonelName_16.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_16.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_16.setObjectName("PersonelName_16")
        self.personel_send_mail_7 = QtWidgets.QPushButton(self.frame_15)
        self.personel_send_mail_7.setGeometry(QtCore.QRect(30, 720, 341, 61))
        self.personel_send_mail_7.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail_7.setObjectName("personel_send_mail_7")
        self.personal_message_4 = QtWidgets.QPushButton(self.frame_15)
        self.personal_message_4.setGeometry(QtCore.QRect(30, 790, 341, 61))
        self.personal_message_4.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personal_message_4.setObjectName("personal_message_4")
        self.personel_send_mail_8 = QtWidgets.QPushButton(self.frame_15)
        self.personel_send_mail_8.setGeometry(QtCore.QRect(30, 570, 341, 61))
        self.personel_send_mail_8.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail_8.setObjectName("personel_send_mail_8")
        self.horizontalLayout.addWidget(self.frame_15)
        self.frame_18 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_18.setEnabled(True)
        self.frame_18.setMinimumSize(QtCore.QSize(400, 900))
        self.frame_18.setMaximumSize(QtCore.QSize(400, 900))
        self.frame_18.setStyleSheet("background-color : rgb(156, 82, 84);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_18 = QtWidgets.QLabel(self.frame_18)
        self.label_18.setGeometry(QtCore.QRect(90, 50, 221, 211))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("ui/robin.jpg"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.PersonelName_25 = QtWidgets.QLabel(self.frame_18)
        self.PersonelName_25.setGeometry(QtCore.QRect(50, 280, 291, 51))
        self.PersonelName_25.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_25.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_25.setObjectName("PersonelName_25")
        self.PersonelName_26 = QtWidgets.QLabel(self.frame_18)
        self.PersonelName_26.setGeometry(QtCore.QRect(90, 330, 211, 51))
        self.PersonelName_26.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_26.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_26.setObjectName("PersonelName_26")
        self.PersonelName_27 = QtWidgets.QLabel(self.frame_18)
        self.PersonelName_27.setGeometry(QtCore.QRect(90, 400, 211, 51))
        self.PersonelName_27.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_27.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_27.setObjectName("PersonelName_27")
        self.PersonelName_28 = QtWidgets.QLabel(self.frame_18)
        self.PersonelName_28.setGeometry(QtCore.QRect(30, 460, 341, 51))
        self.PersonelName_28.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_28.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_28.setObjectName("PersonelName_28")
        self.personel_send_mail_13 = QtWidgets.QPushButton(self.frame_18)
        self.personel_send_mail_13.setGeometry(QtCore.QRect(30, 720, 341, 61))
        self.personel_send_mail_13.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail_13.setObjectName("personel_send_mail_13")
        self.personal_message_7 = QtWidgets.QPushButton(self.frame_18)
        self.personal_message_7.setGeometry(QtCore.QRect(30, 790, 341, 61))
        self.personal_message_7.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personal_message_7.setObjectName("personal_message_7")
        self.personel_send_mail_14 = QtWidgets.QPushButton(self.frame_18)
        self.personel_send_mail_14.setGeometry(QtCore.QRect(30, 570, 341, 61))
        self.personel_send_mail_14.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail_14.setObjectName("personel_send_mail_14")
        self.horizontalLayout.addWidget(self.frame_18)
        self.frame_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_17.setEnabled(True)
        self.frame_17.setMinimumSize(QtCore.QSize(400, 900))
        self.frame_17.setMaximumSize(QtCore.QSize(400, 900))
        self.frame_17.setStyleSheet("background-color : rgb(156, 82, 84);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_17 = QtWidgets.QLabel(self.frame_17)
        self.label_17.setGeometry(QtCore.QRect(90, 50, 221, 211))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("ui/jnniffer.jpg"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.PersonelName_21 = QtWidgets.QLabel(self.frame_17)
        self.PersonelName_21.setGeometry(QtCore.QRect(40, 280, 311, 51))
        self.PersonelName_21.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_21.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_21.setObjectName("PersonelName_21")
        self.PersonelName_22 = QtWidgets.QLabel(self.frame_17)
        self.PersonelName_22.setGeometry(QtCore.QRect(10, 330, 381, 51))
        self.PersonelName_22.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_22.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_22.setObjectName("PersonelName_22")
        self.PersonelName_23 = QtWidgets.QLabel(self.frame_17)
        self.PersonelName_23.setGeometry(QtCore.QRect(90, 400, 211, 51))
        self.PersonelName_23.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_23.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_23.setObjectName("PersonelName_23")
        self.PersonelName_24 = QtWidgets.QLabel(self.frame_17)
        self.PersonelName_24.setGeometry(QtCore.QRect(30, 460, 341, 51))
        self.PersonelName_24.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_24.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_24.setObjectName("PersonelName_24")
        self.personel_send_mail_11 = QtWidgets.QPushButton(self.frame_17)
        self.personel_send_mail_11.setGeometry(QtCore.QRect(30, 720, 341, 61))
        self.personel_send_mail_11.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail_11.setObjectName("personel_send_mail_11")
        self.personal_message_6 = QtWidgets.QPushButton(self.frame_17)
        self.personal_message_6.setGeometry(QtCore.QRect(30, 790, 341, 61))
        self.personal_message_6.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personal_message_6.setObjectName("personal_message_6")
        self.personel_send_mail_12 = QtWidgets.QPushButton(self.frame_17)
        self.personel_send_mail_12.setGeometry(QtCore.QRect(30, 570, 341, 61))
        self.personel_send_mail_12.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail_12.setObjectName("personel_send_mail_12")
        self.horizontalLayout.addWidget(self.frame_17)
        self.frame_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_16.setEnabled(True)
        self.frame_16.setMinimumSize(QtCore.QSize(400, 900))
        self.frame_16.setMaximumSize(QtCore.QSize(400, 900))
        self.frame_16.setStyleSheet("background-color : rgb(156, 82, 84);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_16 = QtWidgets.QLabel(self.frame_16)
        self.label_16.setGeometry(QtCore.QRect(90, 50, 221, 211))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("ui/stacy.jpg"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.PersonelName_17 = QtWidgets.QLabel(self.frame_16)
        self.PersonelName_17.setGeometry(QtCore.QRect(50, 280, 281, 51))
        self.PersonelName_17.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_17.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_17.setObjectName("PersonelName_17")
        self.PersonelName_18 = QtWidgets.QLabel(self.frame_16)
        self.PersonelName_18.setGeometry(QtCore.QRect(90, 330, 211, 51))
        self.PersonelName_18.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_18.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_18.setObjectName("PersonelName_18")
        self.PersonelName_19 = QtWidgets.QLabel(self.frame_16)
        self.PersonelName_19.setGeometry(QtCore.QRect(90, 400, 211, 51))
        self.PersonelName_19.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_19.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_19.setObjectName("PersonelName_19")
        self.PersonelName_20 = QtWidgets.QLabel(self.frame_16)
        self.PersonelName_20.setGeometry(QtCore.QRect(30, 460, 341, 51))
        self.PersonelName_20.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_20.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_20.setObjectName("PersonelName_20")
        self.personel_send_mail_9 = QtWidgets.QPushButton(self.frame_16)
        self.personel_send_mail_9.setGeometry(QtCore.QRect(30, 720, 341, 61))
        self.personel_send_mail_9.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail_9.setObjectName("personel_send_mail_9")
        self.personal_message_5 = QtWidgets.QPushButton(self.frame_16)
        self.personal_message_5.setGeometry(QtCore.QRect(30, 790, 341, 61))
        self.personal_message_5.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personal_message_5.setObjectName("personal_message_5")
        self.personel_send_mail_10 = QtWidgets.QPushButton(self.frame_16)
        self.personel_send_mail_10.setGeometry(QtCore.QRect(30, 570, 341, 61))
        self.personel_send_mail_10.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail_10.setObjectName("personel_send_mail_10")
        self.horizontalLayout.addWidget(self.frame_16)
        self.frame_14 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_14.setEnabled(True)
        self.frame_14.setMinimumSize(QtCore.QSize(400, 900))
        self.frame_14.setMaximumSize(QtCore.QSize(400, 900))
        self.frame_14.setStyleSheet("background-color : rgb(156, 82, 84);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_14 = QtWidgets.QLabel(self.frame_14)
        self.label_14.setGeometry(QtCore.QRect(90, 50, 221, 211))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("ui/barry.jpg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.PersonelName_9 = QtWidgets.QLabel(self.frame_14)
        self.PersonelName_9.setGeometry(QtCore.QRect(20, 280, 361, 51))
        self.PersonelName_9.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_9.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_9.setObjectName("PersonelName_9")
        self.PersonelName_10 = QtWidgets.QLabel(self.frame_14)
        self.PersonelName_10.setGeometry(QtCore.QRect(90, 330, 211, 51))
        self.PersonelName_10.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_10.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_10.setObjectName("PersonelName_10")
        self.PersonelName_11 = QtWidgets.QLabel(self.frame_14)
        self.PersonelName_11.setGeometry(QtCore.QRect(90, 400, 211, 51))
        self.PersonelName_11.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_11.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_11.setObjectName("PersonelName_11")
        self.PersonelName_12 = QtWidgets.QLabel(self.frame_14)
        self.PersonelName_12.setGeometry(QtCore.QRect(30, 460, 341, 51))
        self.PersonelName_12.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.PersonelName_12.setAlignment(QtCore.Qt.AlignCenter)
        self.PersonelName_12.setObjectName("PersonelName_12")
        self.personel_send_mail_5 = QtWidgets.QPushButton(self.frame_14)
        self.personel_send_mail_5.setGeometry(QtCore.QRect(30, 720, 341, 61))
        self.personel_send_mail_5.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail_5.setObjectName("personel_send_mail_5")
        self.personal_message_3 = QtWidgets.QPushButton(self.frame_14)
        self.personal_message_3.setGeometry(QtCore.QRect(30, 790, 341, 61))
        self.personal_message_3.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personal_message_3.setObjectName("personal_message_3")
        self.personel_send_mail_6 = QtWidgets.QPushButton(self.frame_14)
        self.personel_send_mail_6.setGeometry(QtCore.QRect(30, 570, 341, 61))
        self.personel_send_mail_6.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius : 20px;\n"
"font: 14pt \"Nirmala UI Semilight\";\n"
"")
        self.personel_send_mail_6.setObjectName("personel_send_mail_6")
        self.horizontalLayout.addWidget(self.frame_14)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(710, 10, 371, 91))
        self.label_5.setStyleSheet("font: 25 italic 24pt \"Segoe UI Light\";\n"
"color: rgb(125, 125, 125);")
        self.label_5.setObjectName("label_5")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_19 = QtWidgets.QLabel(self.page_4)
        self.label_19.setGeometry(QtCore.QRect(240, 50, 991, 391))
        self.label_19.setStyleSheet("border-radius:20px;\n"
"")
        self.label_19.setLineWidth(3)
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("ui/bank.png"))
        self.label_19.setScaledContents(False)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_4)
        self.label_20.setGeometry(QtCore.QRect(500, 70, 491, 111))
        self.label_20.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.frame_11 = QtWidgets.QFrame(self.page_4)
        self.frame_11.setGeometry(QtCore.QRect(30, 580, 631, 551))
        self.frame_11.setStyleSheet("\n"
"\n"
"background-color: rgb(198, 198, 198);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_11)
        self.scrollArea_2.setGeometry(QtCore.QRect(40, 35, 551, 501))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 580, 680))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_20 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_20.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_20.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_20.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_21 = QtWidgets.QLabel(self.frame_20)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.verticalLayout.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_21.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_21.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_21.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_22 = QtWidgets.QLabel(self.frame_21)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_3.addWidget(self.label_22)
        self.verticalLayout.addWidget(self.frame_21)
        self.frame_28 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_28.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_28.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_28.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_30 = QtWidgets.QLabel(self.frame_28)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_11.addWidget(self.label_30)
        self.verticalLayout.addWidget(self.frame_28)
        self.frame_23 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_23.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_23.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_23.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_24 = QtWidgets.QLabel(self.frame_23)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_5.addWidget(self.label_24)
        self.verticalLayout.addWidget(self.frame_23)
        self.frame_22 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_22.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_22.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_22.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.frame_22)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.verticalLayout.addWidget(self.frame_22)
        self.frame_30 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_30.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_30.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_30.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_33 = QtWidgets.QLabel(self.frame_30)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_14.addWidget(self.label_33)
        self.verticalLayout.addWidget(self.frame_30)
        self.frame_29 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_29.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_29.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_29.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_32 = QtWidgets.QLabel(self.frame_29)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_13.addWidget(self.label_32)
        self.verticalLayout.addWidget(self.frame_29)
        self.frame_27 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_27.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_27.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_27.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_31 = QtWidgets.QLabel(self.frame_27)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_12.addWidget(self.label_31)
        self.verticalLayout.addWidget(self.frame_27)
        self.frame_25 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_25.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_25.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_25.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_27 = QtWidgets.QLabel(self.frame_25)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_8.addWidget(self.label_27)
        self.verticalLayout.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_26.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_26.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_26.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_28 = QtWidgets.QLabel(self.frame_26)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_9.addWidget(self.label_28)
        self.verticalLayout.addWidget(self.frame_26)
        self.frame_24 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_24.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_24.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_24.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_25 = QtWidgets.QLabel(self.frame_24)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.verticalLayout.addWidget(self.frame_24)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.frame_19 = QtWidgets.QFrame(self.page_4)
        self.frame_19.setGeometry(QtCore.QRect(790, 580, 631, 551))
        self.frame_19.setStyleSheet("\n"
"\n"
"background-color: rgb(198, 198, 198);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_19)
        self.scrollArea_3.setGeometry(QtCore.QRect(40, 35, 551, 501))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 580, 680))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_31 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_31.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_31.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_31.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_34 = QtWidgets.QLabel(self.frame_31)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_16.addWidget(self.label_34)
        self.verticalLayout_15.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_32.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_32.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_32.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_35 = QtWidgets.QLabel(self.frame_32)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_17.addWidget(self.label_35)
        self.verticalLayout_15.addWidget(self.frame_32)
        self.frame_33 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_33.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_33.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_33.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_36 = QtWidgets.QLabel(self.frame_33)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_18.addWidget(self.label_36)
        self.verticalLayout_15.addWidget(self.frame_33)
        self.frame_34 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_34.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_34.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_34.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_37 = QtWidgets.QLabel(self.frame_34)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_19.addWidget(self.label_37)
        self.verticalLayout_15.addWidget(self.frame_34)
        self.frame_35 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_35.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_35.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_35.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_38 = QtWidgets.QLabel(self.frame_35)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_20.addWidget(self.label_38)
        self.verticalLayout_15.addWidget(self.frame_35)
        self.frame_36 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_36.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_36.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_36.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_39 = QtWidgets.QLabel(self.frame_36)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_21.addWidget(self.label_39)
        self.verticalLayout_15.addWidget(self.frame_36)
        self.frame_37 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_37.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_37.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_37.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_40 = QtWidgets.QLabel(self.frame_37)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_22.addWidget(self.label_40)
        self.verticalLayout_15.addWidget(self.frame_37)
        self.frame_38 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_38.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_38.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_38.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_41 = QtWidgets.QLabel(self.frame_38)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_23.addWidget(self.label_41)
        self.verticalLayout_15.addWidget(self.frame_38)
        self.frame_39 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_39.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_39.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_39.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_42 = QtWidgets.QLabel(self.frame_39)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_24.addWidget(self.label_42)
        self.verticalLayout_15.addWidget(self.frame_39)
        self.frame_40 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_40.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_40.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_40.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_43 = QtWidgets.QLabel(self.frame_40)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_25.addWidget(self.label_43)
        self.verticalLayout_15.addWidget(self.frame_40)
        self.frame_41 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_41.setMinimumSize(QtCore.QSize(550, 50))
        self.frame_41.setMaximumSize(QtCore.QSize(550, 50))
        self.frame_41.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius : 20px;\n"
"")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_44 = QtWidgets.QLabel(self.frame_41)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_26.addWidget(self.label_44)
        self.verticalLayout_15.addWidget(self.frame_41)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.label_45 = QtWidgets.QLabel(self.page_4)
        self.label_45.setGeometry(QtCore.QRect(180, 510, 321, 41))
        self.label_45.setStyleSheet("font: 75 16pt \"Segoe UI\";\n"
"color: rgb(0, 58, 3);")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.page_4)
        self.label_46.setGeometry(QtCore.QRect(920, 520, 321, 41))
        self.label_46.setStyleSheet("font: 75 16pt \"Segoe UI\";\n"
"color: rgb(144, 3, 3);")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.label_26 = QtWidgets.QLabel(self.page_4)
        self.label_26.setGeometry(QtCore.QRect(700, 70, 91, 31))
        self.label_26.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_26.setObjectName("label_26")
        self.stackedWidget_2.addWidget(self.page_4)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 240, 201, 81))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setStyleSheet("border-radius : 18px;\n"
"background-color : rgb(243, 243, 243);")
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(1610, -20, 161, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("ui/logo.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(1320, 10, 91, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("ui/person_default.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.user_name = QtWidgets.QLabel(self.frame_2)
        self.user_name.setGeometry(QtCore.QRect(1460, 20, 131, 31))
        self.user_name.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.user_name.setObjectName("user_name")
        self.role = QtWidgets.QLabel(self.frame_2)
        self.role.setGeometry(QtCore.QRect(1460, 50, 131, 31))
        self.role.setStyleSheet("font: 7pt \"MS Shell Dlg 2\";")
        self.role.setAlignment(QtCore.Qt.AlignCenter)
        self.role.setObjectName("role")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(1600, 30, 3, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(1170, 20, 91, 81))
        self.pushButton_2.setStyleSheet("border-radius : 8px;")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/notifiacations pnf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(56, 56))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(1060, 20, 91, 81))
        self.pushButton_3.setStyleSheet("border-radius : 8px;")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/message-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(56, 56))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 340, 201, 81))
        self.pushButton_4.setMouseTracking(True)
        self.pushButton_4.setStyleSheet("border-radius : 18px;\n"
"background-color : rgb(243, 243, 243);")
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setChecked(True)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 440, 201, 81))
        self.pushButton_5.setMouseTracking(True)
        self.pushButton_5.setStyleSheet("border-radius : 18px;\n"
"background-color : rgb(243, 243, 243);")
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setChecked(True)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 540, 201, 81))
        self.pushButton_7.setMouseTracking(True)
        self.pushButton_7.setStyleSheet("border-radius : 18px;\n"
"background-color : rgb(243, 243, 243);")
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setChecked(True)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 141, 151))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ui/company_logo_3.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 640, 201, 81))
        self.pushButton_8.setMouseTracking(True)
        self.pushButton_8.setStyleSheet("border-radius : 18px;\n"
"background-color : rgb(243, 243, 243);")
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setChecked(True)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton.raise_()
        self.frame_3.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.user_name.raise_()
        self.role.raise_()
        self.line_2.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_7.raise_()
        self.label_2.raise_()
        self.pushButton_8.raise_()
        self.stackedWidget.addWidget(self.user_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mail_input.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.password_input.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.enter_button.setText(_translate("MainWindow", "LOGIN"))
        self.label.setText(_translate("MainWindow", "Partnered with "))
        self.label_7.setText(_translate("MainWindow", "Financial Courses"))
        self.label_8.setText(_translate("MainWindow", "provided by Plutus"))
        self.label_9.setText(_translate("MainWindow", "Investment and Portfolio Management Specialization"))
        self.label_10.setText(_translate("MainWindow", "Advanced Valuation and Strategy - M&A, Private Equity, and Venture Capital"))
        self.label_11.setText(_translate("MainWindow", "Financial Management Specialization"))
        self.label_12.setText(_translate("MainWindow", "Cryptocurrency and Blockchain: An Introduction to Digital Currencies"))
        self.PersonelName.setText(_translate("MainWindow", "John Smith"))
        self.PersonelName_2.setText(_translate("MainWindow", "Software Developer"))
        self.PersonelName_3.setText(_translate("MainWindow", "$4470"))
        self.PersonelName_4.setText(_translate("MainWindow", "32 Hours/Week"))
        self.personel_send_mail.setText(_translate("MainWindow", "Send Message"))
        self.personal_message.setText(_translate("MainWindow", "Send Mail"))
        self.personel_send_mail_2.setText(_translate("MainWindow", "More Info"))
        self.PersonelName_13.setText(_translate("MainWindow", "Clara McGregor"))
        self.PersonelName_14.setText(_translate("MainWindow", "HR Manager"))
        self.PersonelName_15.setText(_translate("MainWindow", "$5272"))
        self.PersonelName_16.setText(_translate("MainWindow", "33.5 Hours/Week"))
        self.personel_send_mail_7.setText(_translate("MainWindow", "Send Message"))
        self.personal_message_4.setText(_translate("MainWindow", "Send Mail"))
        self.personel_send_mail_8.setText(_translate("MainWindow", "More Info"))
        self.PersonelName_25.setText(_translate("MainWindow", "Robin D. Bushee"))
        self.PersonelName_26.setText(_translate("MainWindow", "Driver"))
        self.PersonelName_27.setText(_translate("MainWindow", "$2492"))
        self.PersonelName_28.setText(_translate("MainWindow", "40 Hours/Week"))
        self.personel_send_mail_13.setText(_translate("MainWindow", "Send Message"))
        self.personal_message_7.setText(_translate("MainWindow", "Send Mail"))
        self.personel_send_mail_14.setText(_translate("MainWindow", "More Info"))
        self.PersonelName_21.setText(_translate("MainWindow", "Jennifer J. Pereira"))
        self.PersonelName_22.setText(_translate("MainWindow", "Senior Software Engineer"))
        self.PersonelName_23.setText(_translate("MainWindow", "$5540"))
        self.PersonelName_24.setText(_translate("MainWindow", "33 Hours/Week"))
        self.personel_send_mail_11.setText(_translate("MainWindow", "Send Message"))
        self.personal_message_6.setText(_translate("MainWindow", "Send Mail"))
        self.personel_send_mail_12.setText(_translate("MainWindow", "More Info"))
        self.PersonelName_17.setText(_translate("MainWindow", "Stacy N. Moore"))
        self.PersonelName_18.setText(_translate("MainWindow", "Intern"))
        self.PersonelName_19.setText(_translate("MainWindow", "$2484"))
        self.PersonelName_20.setText(_translate("MainWindow", "19 Hours/Week"))
        self.personel_send_mail_9.setText(_translate("MainWindow", "Send Message"))
        self.personal_message_5.setText(_translate("MainWindow", "Send Mail"))
        self.personel_send_mail_10.setText(_translate("MainWindow", "More Info"))
        self.PersonelName_9.setText(_translate("MainWindow", "Barry R. Richardson"))
        self.PersonelName_10.setText(_translate("MainWindow", "Accountant"))
        self.PersonelName_11.setText(_translate("MainWindow", "$3995"))
        self.PersonelName_12.setText(_translate("MainWindow", "34 Hours/Week"))
        self.personel_send_mail_5.setText(_translate("MainWindow", "Send Message"))
        self.personal_message_3.setText(_translate("MainWindow", "Send Mail"))
        self.personel_send_mail_6.setText(_translate("MainWindow", "More Info"))
        self.label_5.setText(_translate("MainWindow", "Employer Panel"))
        self.label_20.setText(_translate("MainWindow", "$ 128,335.50"))
        self.label_21.setText(_translate("MainWindow", " Company Name          -       $ 4090         -    02/02/2021"))
        self.label_22.setText(_translate("MainWindow", "aFake productions       -        $3012          -   02/02/2021"))
        self.label_30.setText(_translate("MainWindow", "aFake productions       -        $3012          -   02/02/2021"))
        self.label_24.setText(_translate("MainWindow", " Company Name          -       $ 41020      -    01/02/2021"))
        self.label_23.setText(_translate("MainWindow", " Company Name          -       $ 300         -    01/02/2021"))
        self.label_33.setText(_translate("MainWindow", "aFake productions       -        $31012        -   01/02/2021"))
        self.label_32.setText(_translate("MainWindow", " Company Name          -       $ 7892         -    23/01/2021"))
        self.label_31.setText(_translate("MainWindow", "aFake productions       -        $312          -   22/01/2021"))
        self.label_27.setText(_translate("MainWindow", "COMPANY-NAME          -        AMOUNT          -    DATE"))
        self.label_28.setText(_translate("MainWindow", "COMPANY-NAME          -        AMOUNT          -    DATE"))
        self.label_25.setText(_translate("MainWindow", "COMPANY-NAME          -        AMOUNT          -    DATE"))
        self.label_34.setText(_translate("MainWindow", "aFake productions       -        $3012          -   03/02/2021"))
        self.label_35.setText(_translate("MainWindow", "CompanyLogo             -        $928          -    02/02/2021"))
        self.label_36.setText(_translate("MainWindow", "CompanyLogo             -        $9228          -    02/02/2021"))
        self.label_37.setText(_translate("MainWindow", "CompanyLogo             -        $1928          -    02/02/2021"))
        self.label_38.setText(_translate("MainWindow", "CompanyLogo             -        $92             -    01/02/2021"))
        self.label_39.setText(_translate("MainWindow", "aFake productions       -        $3012          -   01/02/2021"))
        self.label_40.setText(_translate("MainWindow", "aFake productions       -        $3012          -   01/02/2021"))
        self.label_41.setText(_translate("MainWindow", "COMPANY-NAME          -        AMOUNT          -    DATE"))
        self.label_42.setText(_translate("MainWindow", "COMPANY-NAME          -        AMOUNT          -    DATE"))
        self.label_43.setText(_translate("MainWindow", "COMPANY-NAME          -        AMOUNT          -    DATE"))
        self.label_44.setText(_translate("MainWindow", "COMPANY-NAME          -        AMOUNT          -    DATE"))
        self.label_45.setText(_translate("MainWindow", "Income"))
        self.label_46.setText(_translate("MainWindow", "Outcome"))
        self.label_26.setText(_translate("MainWindow", "Current"))
        self.pushButton.setText(_translate("MainWindow", "Home"))
        self.user_name.setText(_translate("MainWindow", "James Smith"))
        self.role.setText(_translate("MainWindow", "CEO"))
        self.pushButton_4.setText(_translate("MainWindow", "Courses"))
        self.pushButton_5.setText(_translate("MainWindow", "Profit/Loss"))
        self.pushButton_7.setText(_translate("MainWindow", "Employers"))
        self.pushButton_8.setText(_translate("MainWindow", "Take Loan"))

from PyQt5 import QtWebEngineWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

